%  issu du Rogers pp 14-15 

I

% q0
si (0) fin }

0

boucle
  
  % q1
  boucle
    si (0) fin }
    G
  }
  D

  % q2
I
  si (0) fin }
  0

  % q3
  si (1) fin }  % inutile
  D

  % q4
  boucle
    si (0) fin }
    D
  }
  D

  % q5
  boucle
    si (0) fin }
    D
  }
  1

  % q6
  boucle
    si (0) fin }
    D
  }
  1

  % q7
  boucle
    si (0) fin }
    G
  }
  G

  % q8
  si (0) fin }
  G

}

I
#

