%  issu du Rogers pp 14-15 
% version 1.finale

I

si (0) fin }                    
0                               
                                
                                
boucle                          
  % (A)
  I
  D                             
  si (0) fin }                  
  0                             
  boucle D si (0) fin } }       
  boucle D si (0) fin } }       
  1                             
  D                             1
  1                             
  boucle G si (0) fin } }       
  boucle G si (0) fin } }       
}
D                               
% (B)

I
#

