%  issu du Rogers pp 14-15 

I

% q0
si (0) fin }
0

boucle
  I % permet de "voir" l'invariant
  
  D

  % q2
  si (0) fin }
  0

  % q3

  % q4
  boucle
    D
    si (0) fin }
  }

  % q5
  boucle
    D
    si (0) fin }
  }
  1

  % q6
  boucle
    D
    si (0) fin }
  }
  1

  % q7
  boucle
    G
    si (0) fin }
  }
  G

  % q8
  si (0) fin }

  % q1
  boucle
    G
    si (0) fin }
  }
}

I
#

